### ISSUE TITLE
Genesis block error + seeds

### ISSUE THREAD

**Issue by le2Ks** [kchirayath/scamcoin#1]
Hi, there is an error when starting the qt wallet, saying that the genesis block is not correct.

Also are the any official nodes? Thanks

**Comment by linkedlist94** [comment]
Currently setting up the official seed nodes, should resolve gen block issue

**Comment by le2Ks** [comment]
> 
> 
> Currently setting up the official seed nodes, should resolve gen block issue

Hi, when starting the wallet, it does not only gives the error. 
It also calculates the right genesis block. 
You can find it in the debug.log file with the merkleroot and nonce.

Here is the result:
- ### genesis:
`c49f65d6cb6d1f3c6bbfdeff9f51b5efa96e29db99fc545636d771b83eab71a4`

- ### merkleroot:
`d83436caf2f9b54e5f356afa0a596227d207f91100a51dda47bd9d96db5461b2`

- ### nonce:
`2085906632`

nTime and zTimespan already are in the main.cpp. Only change the 3 above.

**Comment by linkedlist94** [comment]
it's calculating the gen block because block transaction history is incorrect

**Comment by le2Ks** [comment]
Do you have any addnodes? The wallet won't connect from last commit build
